### ISSUE TITLE
After refreshing the page, the recommended services change

### ISSUE THREAD

**Issue by Marcelinna** [cyfronet-fid/recommender-system#316]
Tested on production version  3.29.0

**Describe the bug**
After refreshing the page, the recommended services change

If the user logged in for the first time in production (new created user)
1. Turn on the filter (7 services are available: EDC EOxHub Workspace, FAIRsharing, fedcloudclient, EGI FedCloud client, ISIDORE, Language Resource Switchboard, MOLGENIS, OpenAIRE Explore Portal)
![image](https://user-images.githubusercontent.com/59872096/150779373-7f56a429-9177-4220-89dc-d9c6defcedd8.png)
2. Refresh page - recommended services are different
![image](https://user-images.githubusercontent.com/59872096/150779440-56731f80-3fd0-4d54-8c2d-22ac37d9b7ef.png)

If the user logged into production before
1. Turn on the filter (7 services are available: EDC EOxHub Workspace, FAIRsharing, fedcloudclient, EGI FedCloud client, ISIDORE, Language Resource Switchboard, MOLGENIS, OpenAIRE Explore Portal)
![image](https://user-images.githubusercontent.com/59872096/150779783-7d0f3f06-2eea-40e6-aa54-b5addf5c2327.png)
2. Refresh page - recommended aren't different
![image](https://user-images.githubusercontent.com/59872096/150779901-50469ea5-7c2d-449b-b5d3-a94d1c97d079.png)

**Comment by Michal-Kolomanski** [comment]
This behaviour is due to the fact that a new user was created that was not in the database on which our recommender was trained. As a result, random services that match the specified categories/scientific domains etc. are returned.
For now, once new data appear in the database, the training process should be repeated. We are planning to improve this process via this ticket: https://github.com/cyfronet-fid/recommender-system/issues/216
